// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBX6AYL3rd5eP8CX9_opUlgbU9aTJ5ns',
    appId: '1:233297659478:web:d5b4ac91399c8236475df7',
    messagingSenderId: '233297659478',
    projectId: 'kit305-14d7f',
    authDomain: 'kit305-14d7f.firebaseapp.com',
    storageBucket: 'kit305-14d7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_kF6cGv2dsF_BSouqNiCsHBn-mtyyBQ',
    appId: '1:233297659478:android:e59af1cd4274768e475df7',
    messagingSenderId: '233297659478',
    projectId: 'kit305-14d7f',
    storageBucket: 'kit305-14d7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhthuy3UGUDl-vR5_x0j7L7vXp1QpJA2I',
    appId: '1:233297659478:ios:867c01b3022c0291475df7',
    messagingSenderId: '233297659478',
    projectId: 'kit305-14d7f',
    storageBucket: 'kit305-14d7f.appspot.com',
    iosClientId: '233297659478-rl6l33muo8dm4ufo9a00irirenkqs3g1.apps.googleusercontent.com',
    iosBundleId: 'au.edu.utas.aludeke.assignment4',
  );
}
